version: '2.3'
services:
  deconvolve:
    build:
      dockerfile: deconvolve/Dockerfile
    runtime: nvidia
    image: 005425916727.dkr.ecr.us-west-2.amazonaws.com/deisseroth-lab/dcon-deconvolve:latest
    volumes:
      - ..:/workspace/dcon

  movie:
    build:
      dockerfile: movie/Dockerfile
    image: 005425916727.dkr.ecr.us-west-2.amazonaws.com/deisseroth-lab/dcon-movie:latest
    volumes:
      - ..:/workspace/dcon
      - $HOME/.aws/credentials:/root/.aws/credentials

  psfs:
    build:
      dockerfile: psfs/Dockerfile
    image: 005425916727.dkr.ecr.us-west-2.amazonaws.com/deisseroth-lab/dcon-psfs:latest
    volumes:
      - ..:/workspace/dcon
      - $HOME/.aws/credentials:/root/.aws/credentials
